services:
  posgres-db:
    image: postgres
    hostname: posgres-database
    networks: 
      - sdb-network
    environment:
      POSTGRES_PASSWORD: 1234

  hammer-gui:
    image: tpcorg/hammerdb:latest-cloudtk
    ports:
      - 8081:8081 
      - 8082:8082 
      - 8080:8080
    networks: 
      - sdb-network
    depends_on:
      - posgres-db
    volumes:
      - ./tcl-scripts:/tcl-scripts

networks:
  sdb-network:
    driver: overlay

