services:
  posgres-db:
    image: postgres
    # need to be able to do restart on container
    hostname: posgres-database
    command: postgres -c config_file=/etc/postgresql/postgresql.conf    
    networks: 
      - sdb-network
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./stats-logs:/exp-logs
      - ./psql-config/postgresql.conf:/etc/postgresql/postgresql.conf

  hammer-gui:
    image: tpcorg/hammerdb:latest-cloudtk
    ports:
      - 8081:8081 
      - 8082:8082 
      - 8080:8080
    networks: 
      - sdb-network
    depends_on:
      - posgres-db
    volumes:
      - ./tcl-scripts:/tcl-scripts
      - ./stats-logs:/exp-logs

networks:
  sdb-network:
    driver: overlay

