# starts the compose file c:
# version: "3"

services:
  database:
    image: mysql
#    command: --mysql-native-password=ON --mysql-native-password-proxy-users 
#    restart: always
    hostname: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks: 
      - sdb-network
    ports:
      - 3306:3306
    volumes:
      - ./mysql-certs:/var/lib/mysql

  hammer-gui:
    image: tpcorg/hammerdb:latest-cloudtk
    ports:
      - 8081:8081 
      - 8082:8082 
      - 8080:8080
    networks: 
      - sdb-network
    depends_on:
      - database
    volumes:
      - ./mysql-certs:/var/lib/mysql

networks:
  sdb-network:
    driver: bridge
